version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - VIRTUAL_HOST=redis.local
    ports:
        - "6379"
  node-app:
    build: ./node-app
    container_name: node_app
    environment:
      - VIRTUAL_HOST=node-app.local
    links:
      - redis
      - flask-api
    ports:
      - "3000:3000"
  flask-api:
    build: ./flask-api
    container_name: flask_api
    environment:
      - VIRTUAL_HOST=flask-api.local
    links:
      - redis
      - orientdb
    ports:
      - "5000:5000"
  orientdb:
    image: brenn/orientdb-spatial:latest
    container_name: orientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
      - VIRTUAL_HOST=orientdb.local
    ports:
      - "2424:2424"
      - "2480:2480"
  wally-core:
    build: ./wally-core
    container_name: wally_core
    environment:
      - VIRTUAL_HOST=wally-core.local
    links:
      - redis
      - orientdb
#  data:
#     volume:
