version: '2'
services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    image: redis:latest
    container_name: redis
    # environment:
    #   - VIRTUAL_HOST=redis.local
    ports:
        - "6379"
  app:
    build: ./app
    container_name: app
    # environment:
    #   - VIRTUAL_HOST=app.local
    links:
      - redis
      - api
    ports:
      - "3000:3000"
  api:
    build: ./api
    container_name: api
    # environment:
    #   - VIRTUAL_HOST=api.local
    links:
      - redis
      - orientdb
    ports:
      - "5000:5000"
  orientdb:
    image: brenn/orientdb-spatial:latest
    container_name: orientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
    #   - VIRTUAL_HOST=orientdb.local
    ports:
      - "2424:2424"
      - "2480:2480"
  wally:
    build: ./wally
    container_name: wally
    # environment:
    #   - VIRTUAL_HOST=wally.local
    links:
      - redis
      - orientdb
#  data:
#     volume:
